module.exports = {
    notificationResult: {
        space: 'notification',
        name: 'notificationResult',
        description: 'Generated by Ping',
        comments: '',
        required: [],
        enforceType: [],
        default: [{key: 'timestamp', formula: 'new Date().getTime()'}],
        model: {
                result: {}, 
                content: {}, 
                scanId: 'string', 
                alertId: 'string'
        }
    }
}